# Generated by Django 6.0.6 on 2026-08-15 06:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Original text entered by the user')),
                ('category', models.CharField(choices=[('Food', 'Food'), ('Expense', 'Expense'), ('Task', 'Task'), ('Event', 'Event'), ('General', 'General')], default='General', max_length=50)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp of when entry was created')),
                ('original_language', models.CharField(default='en', help_text='Language code: en or ta', max_length=10)),
                ('translated_text', models.TextField(blank=True, help_text='English translation if original text was Tamil', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Entries',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('reminder_time', models.TimeField(help_text='Time of day for the reminder (HH:MM)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
